### ISSUE TITLE
Build locally

### ISSUE THREAD

**Issue by henriquelbsouza** [b4k3r/cs16-server#1]
I'm trying to build locally and run the server, but I'm getting the following error:

Console initialized.
Using breakpad crash handler
Setting breakpad minidump AppID = 10
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
FATAL ERROR (shutting down): W_LoadWadFile: couldn't load gfx.wad
email debug.log to linux@valvesoftware.com
Mon Jul  3 18:49:07 UTC 2017: Server restart in 10 seconds

Do you have any information regarding this? I am building locally so I can add amxmodx + plugins... 

But I'm getting this even without any changes :/

What I did was:

docker build

docker run <image ID> and the params you used in the readme (used the server.cfg instead of /cs/cs16_server.cfg)

Thanks :)

**Comment by b4k3r** [comment]
Hi @henriquelbsouza, thanks for feedback. Finally I fixed it.
https://github.com/b4k3r/cs16-server/commit/642ca0414d3e0d79c579a5b16a8e1790a1b74087
Please try again.
