### ISSUE TITLE
Is it possible to run and connect from the same machine (locally)?

### ISSUE THREAD

**Issue by leandrobt2** [b4k3r/cs16-server#3]
The container is running, however, none of the following ips are able to be connected;
```
connect 127.0.0.1:27015
connect 0.0.0.0.1:27015
connect 192.168.0.1000:27015 (ipv4)
connect localhost:27015
```

**Comment by b4k3r** [comment]
Hi @leandrobt2. Thanks for feedback. There was a problem with installing CS 1.6. Now it's fixed https://github.com/b4k3r/cs16-server/commit/642ca0414d3e0d79c579a5b16a8e1790a1b74087. Please try again.
